#!/usr/bin/env python3
"""WildBench quality via WB-Score checklist-guided LLM judge (Lin et al., ICLR 2025).

Prepares OpenAI Batch API request files and parses scored results.
The checklist for each WildBench item is embedded in the parquet's doc["choices"][0]
as a semicolon-separated string. We convert it to a bullet list for the judge prompt.

Two-phase workflow:
  1. --prepare: Build JSONL batch files for the OpenAI Batch API.
  2. --score:   Parse completed batch results and aggregate per-model scores.

Usage:
    python scripts/compute_wildbench_quality.py --prepare [--dry-run]
    python scripts/compute_wildbench_quality.py --score --results-dir DIR
    python scripts/compute_wildbench_quality.py --prepare --runs-dir runs/ --output analysis/judge_batches/wildbench
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd

# ---------------------------------------------------------------------------
# Path setup — reuse project conventions
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parents[1]
_SRC_ROOT = _REPO_ROOT / "src"
if str(_SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(_SRC_ROOT))


# ---------------------------------------------------------------------------
# CoT stripping (same as compute_all_quality.py)
# ---------------------------------------------------------------------------

def _strip_cot(text: str) -> str:
    """Strip chain-of-thought <think> tags from model output."""
    while "<think>" in text and "</think>" in text:
        start = text.find("<think>")
        end = text.find("</think>", start)
        if start != -1 and end != -1:
            text = text[:start] + text[end + len("</think>"):]
        else:
            break
    if "</think>" in text and "<think>" not in text:
        end_idx = text.find("</think>")
        text = text[end_idx + len("</think>"):]
    return text.strip()


# ---------------------------------------------------------------------------
# WB-Score prompt (Lin et al., ICLR 2025) — NO system message, all in user
# ---------------------------------------------------------------------------

WB_SCORE_PROMPT = """# Instruction

You are an expert evaluator. Your task is to evaluate the quality of the responses generated by AI models. We will provide you with the user query and an AI-generated responses. You should first read the user query carefully for analyzing the task, and then evaluate the quality of the responses based on and rules provided below.

## Current User Query
<|begin_of_query|>
{user_query}
<|end_of_query|>

## AI Response
<|begin_of_response|>
{model_output}
<|end_of_response|>

# Evaluation

## Checklist
<|begin_of_checklist|>
{checklist}
<|end_of_checklist|>

Please use this checklist to guide your evaluation, but do not limit your assessment to the checklist.

## Rules

You should compare the above response based on your analysis of the user queries. You should first write down your analysis and the checklist that you used for the evaluation, and then provide your assessment according to the checklist. The scores are in the range of 1~10, where 1 means the response is very poor and 10 means the response is perfect.
Here are more detailed criteria for the scores:
- Score 1~2: The response is very poor and does not make sense at all.
- Score 3~4: The response is poor and does not help user solve the problem in a meaningful way.
- Score 5~6: The response is fair but has some issues (e.g., factual errors, hallucinations, missing key information).
- Score 7~8: The response is good enough but could be improved in some ways.
- Score 9~10: The response is perfect and provides helpful information that can help user solve the problem.

## Output Format
First, please output your analysis for the model response, and then summarize your assessment to two aspects: "strengths" and "weaknesses"; Finally, please write down your rating for the assessment.

Please provide your evaluation results in the following json format by filling in the placeholders in []:
{{"strengths": "[analysis for the strengths of the response]", "weaknesses": "[analysis for the weaknesses of the response]", "score": "[1~10]"}}"""

JUDGE_MODEL = "gpt-4.1-mini"
RUNS_ROOT = Path("runs")
OUTPUT_DIR = Path("analysis/judge_batches/wildbench")
OUTPUT_CSV = Path("analysis/all_wildbench_quality.csv")


# ---------------------------------------------------------------------------
# Discovery — find WildBench parquets
# ---------------------------------------------------------------------------

def discover_wildbench_files(runs_dir: Path) -> Dict[str, Path]:
    """Find parquets containing WildBench task data.

    Searches runs/open_ended/ and runs/no_cot_open_ended/ for parquets
    with 'wildbench' in the task name.

    Returns: {model_name: parquet_path}
    """
    result: Dict[str, Path] = {}
    experiments = ["open_ended", "no_cot_open_ended"]

    for experiment in experiments:
        exp_dir = runs_dir / experiment
        if not exp_dir.is_dir():
            continue
        is_no_cot = experiment.startswith("no_cot_")

        for model_dir in sorted(exp_dir.iterdir()):
            if not model_dir.is_dir():
                continue
            model_name = f"no_cot__{model_dir.name}" if is_no_cot else model_dir.name

            # Search for wildbench parquets in details/
            import glob
            parquet_files = glob.glob(
                str(model_dir / "details" / "**" / "details_*.parquet"),
                recursive=True,
            )
            for pf in sorted(parquet_files):
                fname = Path(pf).name
                if "wildbench" in fname.lower():
                    result[model_name] = Path(pf)
                    break  # one per model

            # Fallback: task-specific JSONL
            if model_name not in result:
                jsonl_path = model_dir / "diversity_generations_wildbench_diversity.jsonl"
                if jsonl_path.exists():
                    result[model_name] = jsonl_path

    return result


# ---------------------------------------------------------------------------
# Loading — extract records from WildBench parquets
# ---------------------------------------------------------------------------

def load_wildbench_records(path: Path) -> List[Dict[str, Any]]:
    """Load a WildBench parquet and extract gen-0, query, and checklist.

    Each record contains:
      - query: the user query (from doc["query"])
      - checklist_text: bullet-formatted checklist (from doc["choices"][0])
      - output: first generation (gen-0), CoT-stripped
      - raw_output: first generation without stripping
      - idx: row index for tracing
    """
    df = pd.read_parquet(path)
    records = []

    for idx, row in df.iterrows():
        doc = row["doc"]
        mr = row["model_response"]

        # Extract query
        query = doc.get("query", "")
        if not query:
            continue

        # Extract checklist from choices[0] — semicolon-separated
        raw_choices = doc.get("choices", [])
        if hasattr(raw_choices, "tolist"):
            raw_choices = raw_choices.tolist()

        checklist_raw = ""
        if raw_choices and len(raw_choices) > 0:
            checklist_raw = str(raw_choices[0])

        # Convert semicolon-separated checklist to bullet list
        if checklist_raw.strip():
            checklist_items = checklist_raw.strip().split("; ")
            checklist_text = "\n".join(
                f"- {item}" for item in checklist_items if item.strip()
            )
        else:
            checklist_text = "- No specific checklist provided."

        # Extract generation-0
        raw_outputs = mr.get("text", []) if isinstance(mr, dict) else []
        if hasattr(raw_outputs, "tolist"):
            raw_outputs = raw_outputs.tolist()

        if not raw_outputs:
            continue

        raw_output = str(raw_outputs[0])
        stripped_output = _strip_cot(raw_output)

        records.append({
            "query": query,
            "checklist_text": checklist_text,
            "output": stripped_output,
            "raw_output": raw_output,
            "idx": int(idx),
        })

    return records


_WILDBENCH_CHECKLIST_INDEX: Optional[Dict[str, str]] = None


def _get_wildbench_checklist_index() -> Dict[str, str]:
    """Build prompt-prefix -> checklist index from HF WildBench dataset."""
    global _WILDBENCH_CHECKLIST_INDEX
    if _WILDBENCH_CHECKLIST_INDEX is not None:
        return _WILDBENCH_CHECKLIST_INDEX
    from datasets import load_dataset
    ds = load_dataset("allenai/WildBench", "v2", split="test")
    index = {}
    for row in ds:
        conv = row.get("conversation_input", [])
        if conv and isinstance(conv, list) and len(conv) > 0:
            query = conv[-1].get("content", "") if isinstance(conv[-1], dict) else str(conv[-1])
        else:
            query = ""
        key = query[:200].strip()
        checklist = row.get("checklist", [])
        if checklist:
            index[key] = "\n".join(f"- {item}" for item in checklist if item.strip())
    _WILDBENCH_CHECKLIST_INDEX = index
    return index


def load_wildbench_jsonl(path: Path) -> List[Dict[str, Any]]:
    """Load WildBench records from JSONL, fetching checklists from HF."""
    checklist_index = _get_wildbench_checklist_index()
    records = []
    seen: set = set()
    with path.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            task = r.get("task", "").split("|")[0]
            if "wildbench" not in task:
                continue
            input_id = str(r.get("input_id", ""))
            if input_id in seen:
                continue
            seen.add(input_id)
            outputs = r.get("outputs", [])
            if not outputs:
                continue
            raw_output = str(outputs[0])
            stripped = _strip_cot(raw_output)
            prompt = r.get("prompt", "")
            # Lookup checklist from HF
            checklist_text = checklist_index.get(
                prompt[:200].strip(),
                "- No specific checklist provided."
            )
            records.append({
                "query": prompt,
                "checklist_text": checklist_text,
                "output": stripped,
                "raw_output": raw_output,
                "idx": len(records),
            })
    return records


def load_wildbench_data(path: Path) -> List[Dict[str, Any]]:
    """Load WildBench records from parquet or JSONL."""
    if path.suffix == ".parquet":
        return load_wildbench_records(path)
    return load_wildbench_jsonl(path)


# ---------------------------------------------------------------------------
# Prepare — build OpenAI Batch API JSONL files
# ---------------------------------------------------------------------------

def _make_custom_id(model_name: str, idx: int) -> str:
    """Build a custom_id for batch requests: MODEL||wildbench||IDX."""
    return f"{model_name}||wildbench||{idx}"


def _parse_custom_id(custom_id: str) -> Tuple[str, int]:
    """Parse custom_id back into (model_name, idx)."""
    parts = custom_id.split("||")
    if len(parts) != 3 or parts[1] != "wildbench":
        raise ValueError(f"Unexpected custom_id format: {custom_id}")
    return parts[0], int(parts[2])


def prepare(args: argparse.Namespace) -> None:
    """Build WB-Score batch request JSONL files for the OpenAI Batch API.

    Creates one JSONL per model in OUTPUT_DIR, each line being a single
    Batch API request for judging gen-0 of one WildBench item.
    """
    runs_dir = Path(args.runs_dir)
    output_dir = Path(args.output)

    print("Discovering WildBench parquets...")
    model_files = discover_wildbench_files(runs_dir)
    print(f"Found {len(model_files)} models with WildBench data")

    if not model_files:
        print("No WildBench parquets found. Exiting.")
        return

    output_dir.mkdir(parents=True, exist_ok=True)
    total_requests = 0

    for model_name, parquet_path in sorted(model_files.items()):
        records = load_wildbench_data(parquet_path)
        print(f"  {model_name}: {len(records)} records from {parquet_path.name}")

        if not records:
            continue

        # Build batch JSONL
        # Sanitize model name for filename
        safe_name = model_name.replace("/", "__").replace(" ", "_")
        batch_path = output_dir / f"{safe_name}.jsonl"

        if args.dry_run:
            print(f"    [dry-run] Would write {len(records)} requests to {batch_path}")
            total_requests += len(records)
            continue

        lines = []
        for record in records:
            prompt = WB_SCORE_PROMPT.format(
                user_query=record["query"],
                model_output=record["output"],
                checklist=record["checklist_text"],
            )

            request = {
                "custom_id": _make_custom_id(model_name, record["idx"]),
                "method": "POST",
                "url": "/v1/chat/completions",
                "body": {
                    "model": JUDGE_MODEL,
                    "messages": [
                        {"role": "user", "content": prompt},
                    ],
                    "temperature": 0,
                    "max_tokens": 1024,
                },
            }
            lines.append(json.dumps(request, ensure_ascii=False))

        batch_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        total_requests += len(lines)
        print(f"    Wrote {len(lines)} requests to {batch_path}")

    print(f"\nTotal: {total_requests} judge requests across {len(model_files)} models")
    if not args.dry_run:
        print(f"Batch files saved to {output_dir}/")
        print("\nNext steps:")
        print("  1. Upload each JSONL to the OpenAI Batch API")
        print("  2. Download completed results to a results directory")
        print(f"  3. Run: python {__file__} --score --results-dir <DIR>")


# ---------------------------------------------------------------------------
# Score parsing
# ---------------------------------------------------------------------------

def parse_score(text: str) -> Optional[int]:
    """Extract numeric score from judge response.

    Tries JSON parsing first, then falls back to regex.
    Returns score as int in [1, 10], or None if parsing fails.
    """
    if not text or not text.strip():
        return None

    # Strategy 1: find JSON object in the response and parse it
    # Look for the last JSON-like block (judge may output analysis first)
    json_matches = re.findall(r'\{[^{}]*"score"[^{}]*\}', text, re.DOTALL)
    for candidate in reversed(json_matches):
        try:
            parsed = json.loads(candidate)
            score_val = parsed.get("score")
            if score_val is not None:
                # Handle both "7" and 7
                score_int = int(str(score_val).strip().strip('"'))
                if 1 <= score_int <= 10:
                    return score_int
        except (json.JSONDecodeError, ValueError, TypeError):
            continue

    # Strategy 2: regex fallback for malformed JSON
    match = re.search(r'"score"\s*:\s*"?(\d+)"?', text)
    if match:
        score_int = int(match.group(1))
        if 1 <= score_int <= 10:
            return score_int

    # Strategy 3: look for bare "Score: N" pattern
    match = re.search(r'[Ss]core\s*[:=]\s*(\d+)', text)
    if match:
        score_int = int(match.group(1))
        if 1 <= score_int <= 10:
            return score_int

    return None


# ---------------------------------------------------------------------------
# Score — aggregate results from completed batch
# ---------------------------------------------------------------------------

def score(args: argparse.Namespace) -> None:
    """Read completed batch results, parse scores, and aggregate per model.

    Reads all JSONL files in --results-dir, extracts scores, and produces
    a summary CSV with per-model statistics.

    WB-Score normalization (Lin et al.): wb_score = (raw - 5) * 2
    This maps [1,10] to [-8,10] with 5 as the neutral point.
    """
    results_dir = Path(args.results_dir)
    output_csv = Path(args.output_csv)

    if not results_dir.is_dir():
        raise SystemExit(f"Results directory not found: {results_dir}")

    # Collect all results across JSONL files
    model_scores: Dict[str, List[int]] = defaultdict(list)
    model_parse_errors: Dict[str, int] = defaultdict(int)
    total_parsed = 0
    total_errors = 0

    result_files = sorted(results_dir.glob("*.jsonl"))
    if not result_files:
        raise SystemExit(f"No JSONL files found in {results_dir}")

    print(f"Reading {len(result_files)} result files from {results_dir}")

    for rf in result_files:
        with rf.open(encoding="utf-8") as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    print(f"  Warning: invalid JSON at {rf.name}:{line_num}")
                    total_errors += 1
                    continue

                custom_id = record.get("custom_id", "")
                try:
                    model_name, idx = _parse_custom_id(custom_id)
                except ValueError:
                    print(f"  Warning: unexpected custom_id: {custom_id}")
                    total_errors += 1
                    continue

                # Extract judge response text
                response = record.get("response", {})
                body = response.get("body", {})
                choices = body.get("choices", [])
                if not choices:
                    model_parse_errors[model_name] += 1
                    total_errors += 1
                    continue

                judge_text = choices[0].get("message", {}).get("content", "")
                score_val = parse_score(judge_text)

                if score_val is not None:
                    model_scores[model_name].append(score_val)
                    total_parsed += 1
                else:
                    model_parse_errors[model_name] += 1
                    total_errors += 1

    print(f"\nParsed {total_parsed} scores, {total_errors} errors")

    if not model_scores:
        print("No valid scores found. Exiting.")
        return

    # Build summary DataFrame
    rows = []
    for model_name in sorted(model_scores.keys()):
        scores = model_scores[model_name]
        n = len(scores)
        raw_mean = sum(scores) / n
        raw_std = (sum((s - raw_mean) ** 2 for s in scores) / max(n - 1, 1)) ** 0.5
        sorted_scores = sorted(scores)
        raw_median = (
            sorted_scores[n // 2]
            if n % 2 == 1
            else (sorted_scores[n // 2 - 1] + sorted_scores[n // 2]) / 2.0
        )
        # WB-Score normalization: (raw - 5) * 2
        wb_score = (raw_mean - 5.0) * 2.0

        n_errors = model_parse_errors.get(model_name, 0)

        rows.append({
            "model": model_name,
            "n_scored": n,
            "n_parse_errors": n_errors,
            "raw_mean": raw_mean,
            "raw_std": raw_std,
            "raw_median": raw_median,
            "wb_score": wb_score,
        })

        print(
            f"  {model_name}: n={n}, raw_mean={raw_mean:.2f} +/- {raw_std:.2f}, "
            f"median={raw_median:.1f}, wb_score={wb_score:.2f}, "
            f"parse_errors={n_errors}"
        )

    df = pd.DataFrame(rows)
    col_order = [
        "model", "n_scored", "n_parse_errors",
        "raw_mean", "raw_std", "raw_median", "wb_score",
    ]
    df = df[[c for c in col_order if c in df.columns]]

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_csv, index=False, float_format="%.4f")
    print(f"\nSaved aggregated scores to {output_csv}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="WildBench quality via WB-Score checklist-guided LLM judge.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  # Prepare batch files (dry run first):
  python scripts/compute_wildbench_quality.py --prepare --dry-run

  # Prepare batch files for real:
  python scripts/compute_wildbench_quality.py --prepare

  # Score completed results:
  python scripts/compute_wildbench_quality.py --score --results-dir analysis/judge_batches/wildbench_results/
""",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--prepare", action="store_true",
        help="Build OpenAI Batch API request JSONL files",
    )
    mode.add_argument(
        "--score", action="store_true",
        help="Parse completed batch results and aggregate scores",
    )
    parser.add_argument(
        "--runs-dir", type=str, default="runs",
        help="Root runs directory (default: runs/)",
    )
    parser.add_argument(
        "--results-dir", type=str, default="",
        help="Directory containing completed batch result JSONL files (required for --score)",
    )
    parser.add_argument(
        "--output", type=str, default=str(OUTPUT_DIR),
        help=f"Output directory for batch files (default: {OUTPUT_DIR})",
    )
    parser.add_argument(
        "--output-csv", type=str, default=str(OUTPUT_CSV),
        help=f"Output CSV path for aggregated scores (default: {OUTPUT_CSV})",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="List what would be prepared without writing files",
    )

    args = parser.parse_args()

    if args.score and not args.results_dir:
        parser.error("--results-dir is required when using --score")

    return args


def main() -> None:
    args = parse_args()

    if args.prepare:
        prepare(args)
    elif args.score:
        score(args)


if __name__ == "__main__":
    main()
